apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-test-app
  name: flask-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-test-app
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-test-app
    spec:
      containers:
        - image: shakibaam/weather_docker:2.0
          name: flask-test-app
          resources: { }
          ports:
            - containerPort: 8080
          volumeMounts:
           - mountPath: /env/.env
             subPath: .env
             name: config-map
             readOnly: true
      volumes:
        - name: config-map
          configMap:
            name: flask-configmap
status: { }
